# Netlify configuration for deploying the frontend and proxying API calls
# IMPORTANT: Replace the backend URL below after you deploy your backend (e.g. Render)
# Example backend URL: https://qwipo-backend.onrender.com

[build]
  command = "npm run build"
  publish = "dist"

# Proxy all /api/* requests to your deployed backend
[[redirects]]
  from = "/api/*"
  to = "https://YOUR_BACKEND_URL/api/:splat"
  status = 200
  force = true
