# Netlify configuration for deploying the frontend and proxying API calls
# Backend URL (Render): https://qwipo-backend-lzed.onrender.com

[build]
  command = "npm run build"
  publish = "dist"

# Proxy all /api/* requests to your deployed backend
[[redirects]]
  from = "/api/*"
  to = "https://qwipo-backend-lzed.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback: route all non-API paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
